import React from "react";
import { Header, Footer, Container, Section } from "@/components/layout";
import { Heading, Text, Card } from "@/components/ui";
import { CornerMarks, SquigglyLine } from "@/components/decorations/hand-drawn-elements";
import { ScrollText } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-grow">
                <Section background="alt" className="pt-20 pb-16 relative overflow-hidden">
                    <Container className="text-center">
                        <div className="w-16 h-16 wobbly-sm bg-accent-secondary/10 flex items-center justify-center mx-auto mb-6">
                            <ScrollText className="w-8 h-8 text-accent-secondary" />
                        </div>
                        <Heading level="h1" decoration="underline" className="mb-6">
                            Terms of Service
                        </Heading>
                        <Text size="xl" variant="muted" className="max-w-2xl mx-auto">
                            The legal sketch of how we work together. By using StellarApply, you agree to these ground rules.
                        </Text>
                    </Container>
                </Section>

                <Section className="py-20">
                    <Container size="md">
                        <Card variant="default" padding="lg" decoration="tack">
                            <CornerMarks className="text-accent-secondary/20" />
                            <div className="prose prose-lg dark:prose-invert max-w-none space-y-12">
                                <section>
                                    <Heading level="h3" className="mb-4">1. Acceptance of Terms</Heading>
                                    <Text className="leading-relaxed">
                                        By accessing StellarApply.ai, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.
                                    </Text>
                                </section>

                                <section>
                                    <Heading level="h3" className="mb-4">2. Use License</Heading>
                                    <Text className="leading-relaxed">
                                        StellarApply grants you a personal, non-exclusive license to use our AI tools for your job search. You may not use our sketches for commercial resale or to build a competing service that is "sketchily" similar.
                                    </Text>
                                </section>

                                <section>
                                    <Heading level="h3" className="mb-4">3. Accuracy of AI Sketches</Heading>
                                    <Text className="leading-relaxed">
                                        While our AI is brilliant, it can sometimes "hallucinate" or miss details. You are solely responsible for reviewing and verifying the accuracy of any resume or letter generated by our system before sending it to an employer.
                                    </Text>
                                </section>

                                <section>
                                    <Heading level="h3" className="mb-4">4. Limitations</Heading>
                                    <Text className="leading-relaxed">
                                        StellarApply shall not be held liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on our website.
                                    </Text>
                                </section>

                                <div className="pt-12 text-center">
                                    <SquigglyLine className="mx-auto w-32 mb-4 text-border/30" />
                                    <Text variant="subtle" size="sm">
                                        Legal Ink Dried: February 2026
                                    </Text>
                                </div>
                            </div>
                        </Card>
                    </Container>
                </Section>
            </main>
            <Footer />
        </div>
    );
}