<<<<<<< HEAD
import React from "react";
import { Header, Footer, Container, Section } from "@/components/layout";
import { Heading, Text, Card } from "@/components/ui";
import { CornerMarks, SquigglyLine } from "@/components/decorations/hand-drawn-elements";
import { ScrollText } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-grow">
                <Section background="alt" className="pt-20 pb-16 relative overflow-hidden">
                    <Container className="text-center">
                        <div className="w-16 h-16 wobbly-sm bg-accent-secondary/10 flex items-center justify-center mx-auto mb-6">
                            <ScrollText className="w-8 h-8 text-accent-secondary" />
                        </div>
                        <Heading level="h1" decoration="underline" className="mb-6">
                            Terms of Service
                        </Heading>
                        <Text size="xl" variant="muted" className="max-w-2xl mx-auto">
                            The legal sketch of how we work together. By using StellarApply, you agree to these ground rules.
                        </Text>
                    </Container>
                </Section>

                <Section className="py-20">
                    <Container size="md">
                        <Card variant="default" padding="lg" decoration="tack">
                            <CornerMarks className="text-accent-secondary/20" />
                            <div className="prose prose-lg dark:prose-invert max-w-none space-y-12">
                                <section>
                                    <Heading level="h3" className="mb-4">1. Acceptance of Terms</Heading>
                                    <Text className="leading-relaxed">
                                        By accessing StellarApply.ai, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.
                                    </Text>
                                </section>

                                <section>
                                    <Heading level="h3" className="mb-4">2. Use License</Heading>
                                    <Text className="leading-relaxed">
                                        StellarApply grants you a personal, non-exclusive license to use our AI tools for your job search. You may not use our sketches for commercial resale or to build a competing service that is "sketchily" similar.
                                    </Text>
                                </section>

                                <section>
                                    <Heading level="h3" className="mb-4">3. Accuracy of AI Sketches</Heading>
                                    <Text className="leading-relaxed">
                                        While our AI is brilliant, it can sometimes "hallucinate" or miss details. You are solely responsible for reviewing and verifying the accuracy of any resume or letter generated by our system before sending it to an employer.
                                    </Text>
                                </section>

                                <section>
                                    <Heading level="h3" className="mb-4">4. Limitations</Heading>
                                    <Text className="leading-relaxed">
                                        StellarApply shall not be held liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on our website.
                                    </Text>
                                </section>

                                <div className="pt-12 text-center">
                                    <SquigglyLine className="mx-auto w-32 mb-4 text-border/30" />
                                    <Text variant="subtle" size="sm">
                                        Legal Ink Dried: February 2026
                                    </Text>
                                </div>
                            </div>
                        </Card>
                    </Container>
                </Section>
            </main>
            <Footer />
        </div>
    );
}
=======
"use client";

import Link from "next/link";
import { SketchCard, SketchButton } from "@/components/ui/hand-drawn";
import { ArrowLeft, Scale } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-paper-bg p-8 md:p-16">
            <div className="max-w-4xl mx-auto">
                <Link href="/">
                    <SketchButton variant="secondary" className="mb-12 flex items-center gap-2">
                        <ArrowLeft className="w-5 h-5" /> Back to Home
                    </SketchButton>
                </Link>

                <SketchCard decoration="tack" color="white" className="p-10 md:p-16 space-y-8">
                    <div className="flex items-center gap-4 mb-8">
                        <div className="w-16 h-16 wobble bg-marker-red/10 flex items-center justify-center">
                            <Scale className="w-10 h-10 text-marker-red" strokeWidth={3} />
                        </div>
                        <h1 className="text-5xl md:text-6xl font-marker rotate-1">Terms of Service</h1>
                    </div>

                    <div className="prose prose-xl font-handwritten text-pencil-black/90 space-y-6">
                        <p className="text-2xl italic mb-8 underline decoration-marker-red decoration-wavy underline-offset-8">
                            By using Stellapply, you agree to these rules. They're like gravity—you can't ignore them.
                        </p>

                        <section className="space-y-4">
                            <h2 className="text-3xl font-marker border-b-2 border-dashed border-pencil-black/20 pb-2">1. The Basics</h2>
                            <p>
                                You must be human (or a very advanced robot with permission).
                                You are responsible for any job offers you get (and the celebrations that follow).
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-3xl font-marker border-b-2 border-dashed border-pencil-black/20 pb-2">2. Prohibited Acts</h2>
                            <p>
                                Don't try to hack our sketches. Don't use the AI to apply for jobs you definitely
                                aren't qualified for (like "King of Mars" or "Dragon Tamer").
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-3xl font-marker border-b-2 border-dashed border-pencil-black/20 pb-2">3. Limitation of Liability</h2>
                            <p>
                                We provide the tools, you provide the talent. We aren't responsible if you
                                accidentally get hired by a company you don't like. Choose wisely!
                            </p>
                        </section>

                        <div className="pt-12 text-center text-pencil-black/40">
                            <p>Agreement effective: Upon your first doodle.</p>
                        </div>
                    </div>
                </SketchCard>
            </div>
        </div>
    );
}
>>>>>>> feature/resume-upload-gdpr-compliance
