"""add_missing_persona_columns

Revision ID: 16de139f8365
Revises: ecc6b0fa9ff1
Create Date: 2026-02-14 12:22:08.116735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.core.security.encryption

# revision identifiers, used by Alembic.
revision: str = "16de139f8365"
down_revision: Union[str, Sequence[str], None] = "ecc6b0fa9ff1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_usage_records",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("billing_period", sa.String(length=7), nullable=False),
        sa.Column("applications_submitted", sa.Integer(), nullable=False),
        sa.Column("agent_applications", sa.Integer(), nullable=False),
        sa.Column("manual_applications", sa.Integer(), nullable=False),
        sa.Column("ai_calls_made", sa.Integer(), nullable=False),
        sa.Column("resumes_generated", sa.Integer(), nullable=False),
        sa.Column("cover_letters_generated", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_usage_records_user_id"),
        "billing_usage_records",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_usage_user_period",
        "billing_usage_records",
        ["user_id", "billing_period"],
        unique=True,
    )
    op.create_table(
        "application_credentials",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("portal_url", sa.String(length=1024), nullable=False),
        sa.Column("portal_name", sa.String(length=255), nullable=True),
        sa.Column(
            "email_used", src.core.security.encryption.EncryptedString(), nullable=False
        ),
        sa.Column(
            "password", src.core.security.encryption.EncryptedString(), nullable=False
        ),
        sa.Column("account_created", sa.Boolean(), nullable=False),
        sa.Column("login_url", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_credentials_application_id"),
        "application_credentials",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "application_form_data",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("page_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "form_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("screenshot_url", sa.String(length=1024), nullable=True),
        sa.Column("submitted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_form_data_application_id"),
        "application_form_data",
        ["application_id"],
        unique=False,
    )
    op.add_column("applications", sa.Column("match_score", sa.Float(), nullable=True))
    op.add_column(
        "applications",
        sa.Column("generated_cv_url", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column("generated_cover_letter_url", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column(
            "application_email",
            src.core.security.encryption.EncryptedString(),
            nullable=True,
        ),
    )
    op.add_column(
        "applications", sa.Column("agent_session_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "applications",
        sa.Column(
            "is_agent_applied",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.drop_index(
        op.f("ix_applications_user_created_at_desc"), table_name="applications"
    )
    op.create_index(
        "ix_applications_user_created_at_desc",
        "applications",
        ["user_id", "created_at"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_index(
        "ix_applications_agent_session",
        "applications",
        ["agent_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_agent_session_id"),
        "applications",
        ["agent_session_id"],
        unique=False,
    )
    op.add_column(
        "personas",
        sa.Column(
            "application_email",
            src.core.security.encryption.EncryptedString(),
            nullable=True,
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "use_login_email_for_applications",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    op.drop_index(op.f("ix_resumes_user_id_created_at_desc"), table_name="resumes")
    op.create_index(
        "ix_resumes_user_id_created_at_desc",
        "resumes",
        ["user_id", "created_at"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_resumes_user_id_created_at_desc",
        table_name="resumes",
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_index(
        op.f("ix_resumes_user_id_created_at_desc"),
        "resumes",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_column("personas", "use_login_email_for_applications")
    op.drop_column("personas", "application_email")
    op.drop_index(op.f("ix_applications_agent_session_id"), table_name="applications")
    op.drop_index("ix_applications_agent_session", table_name="applications")
    op.drop_index(
        "ix_applications_user_created_at_desc",
        table_name="applications",
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_index(
        op.f("ix_applications_user_created_at_desc"),
        "applications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_column("applications", "is_agent_applied")
    op.drop_column("applications", "agent_session_id")
    op.drop_column("applications", "application_email")
    op.drop_column("applications", "generated_cover_letter_url")
    op.drop_column("applications", "generated_cv_url")
    op.drop_column("applications", "match_score")
    op.drop_index(
        op.f("ix_application_form_data_application_id"),
        table_name="application_form_data",
    )
    op.drop_table("application_form_data")
    op.drop_index(
        op.f("ix_application_credentials_application_id"),
        table_name="application_credentials",
    )
    op.drop_table("application_credentials")
    op.drop_index("ix_usage_user_period", table_name="billing_usage_records")
    op.drop_index(
        op.f("ix_billing_usage_records_user_id"), table_name="billing_usage_records"
    )
    op.drop_table("billing_usage_records")
    # ### end Alembic commands ###
