"""feat: add immutable audit logging with append-only triggers

Revision ID: 216520bc1d06
Revises: 489c2e7d2ba3
Create Date: 2026-02-01 15:04:50.990337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "216520bc1d06"
down_revision: Union[str, Sequence[str], None] = "489c2e7d2ba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "READ",
                "UPDATE",
                "DELETE",
                "EXPORT",
                "LOGIN",
                "LOGOUT",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("ip_address_encrypted", sa.Text(), nullable=False),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=50), nullable=False),
        sa.Column("old_value_encrypted", sa.Text(), nullable=True),
        sa.Column("new_value_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("hash_chain", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Enforce append-only behavior
    op.execute("""
        CREATE OR REPLACE FUNCTION prevent_audit_log_modification()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'Audit logs are immutable and cannot be updated or deleted.';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER enforce_append_only_audit_log
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW
        EXECUTE FUNCTION prevent_audit_log_modification();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS enforce_append_only_audit_log ON audit_events;")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_log_modification();")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
