"""feat: implement persona module tables with encryption and vectors

Revision ID: 6e7a4aeb9d95
Revises: 216520bc1d06
Create Date: 2026-02-01 15:10:03.179921

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import src.core.security.encryption

# revision identifiers, used by Alembic.
revision: str = "6e7a4aeb9d95"
down_revision: str | Sequence[str] | None = "216520bc1d06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM types manually if they are used in add_column but not create_table
    sa.Enum(
        "CITIZEN",
        "PERMANENT_RESIDENT",
        "H1B",
        "L1",
        "F1_OPT",
        "J1",
        "TN",
        "OTHER",
        "NOT_REQUIRED",
        name="workauthorization",
    ).create(op.get_bind())
    sa.Enum("REMOTE", "HYBRID", "ONSITE", "ANY", name="remotepreference").create(
        op.get_bind()
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persona_behavioral_answers",
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "CHALLENGE",
                "ACHIEVEMENT",
                "FAILURE",
                "LEADERSHIP",
                "TEAMWORK",
                "CONFLICT",
                "GENERAL",
                name="questiontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "answer", src.core.security.encryption.EncryptedString(), nullable=False
        ),
        sa.Column(
            "answer_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persona_behavioral_answers_persona_id"),
        "persona_behavioral_answers",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "persona_career_preferences",
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("target_titles", sa.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column("target_industries", sa.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column(
            "company_sizes",
            sa.ARRAY(
                sa.Enum(
                    "STARTUP",
                    "SMALL",
                    "MEDIUM",
                    "LARGE",
                    "ENTERPRISE",
                    name="companysize",
                )
            ),
            nullable=False,
        ),
        sa.Column(
            "blacklisted_companies", sa.ARRAY(sa.String(length=255)), nullable=False
        ),
        sa.Column("dream_companies", sa.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persona_career_preferences_persona_id"),
        "persona_career_preferences",
        ["persona_id"],
        unique=True,
    )
    op.create_table(
        "persona_educations",
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("institution_name", sa.String(length=255), nullable=False),
        sa.Column(
            "degree_type",
            sa.Enum(
                "HIGH_SCHOOL",
                "ASSOCIATE",
                "BACHELOR",
                "MASTER",
                "DOCTORATE",
                "PROFESSIONAL",
                "CERTIFICATION",
                "OTHER",
                name="degreetype",
            ),
            nullable=False,
        ),
        sa.Column("field_of_study", sa.String(length=255), nullable=False),
        sa.Column("graduation_date", sa.Date(), nullable=False),
        sa.Column("gpa", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persona_educations_persona_id"),
        "persona_educations",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "persona_experiences",
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("job_title", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("achievements", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("skills_used", sa.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column(
            "experience_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=384),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persona_experiences_persona_id"),
        "persona_experiences",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "persona_skills",
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "category",
            sa.Enum("TECHNICAL", "SOFT", "TOOL", "LANGUAGE", name="skillcategory"),
            nullable=False,
        ),
        sa.Column("proficiency_level", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persona_skills_name"), "persona_skills", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_persona_skills_persona_id"),
        "persona_skills",
        ["persona_id"],
        unique=False,
    )
    op.add_column("job_matches", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.add_column("job_matches", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.add_column(
        "job_matches",
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
    )
    op.alter_column(
        "job_matches",
        "created_by",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="created_by::uuid",
    )
    op.drop_column("job_matches", "is_deleted")
    op.add_column("jobs", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.add_column("jobs", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.add_column(
        "jobs", sa.Column("version", sa.Integer(), nullable=False, server_default="1")
    )
    op.alter_column(
        "jobs",
        "created_by",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="created_by::uuid",
    )
    op.drop_column("jobs", "is_deleted")
    op.add_column(
        "personas",
        sa.Column(
            "full_name",
            src.core.security.encryption.EncryptedString(length=255),
            nullable=False,
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "email",
            src.core.security.encryption.EncryptedString(length=255),
            nullable=False,
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "phone",
            src.core.security.encryption.EncryptedString(length=50),
            nullable=True,
        ),
    )
    op.add_column(
        "personas", sa.Column("location_city", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "personas", sa.Column("location_state", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "personas", sa.Column("location_country", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "personas",
        sa.Column(
            "work_authorization",
            sa.Enum(
                "CITIZEN",
                "PERMANENT_RESIDENT",
                "H1B",
                "L1",
                "F1_OPT",
                "J1",
                "TN",
                "OTHER",
                "NOT_REQUIRED",
                name="workauthorization",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "remote_preference",
            sa.Enum("REMOTE", "HYBRID", "ONSITE", "ANY", name="remotepreference"),
            nullable=False,
        ),
    )
    op.add_column("personas", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.add_column("personas", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.add_column(
        "personas",
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
    )
    op.alter_column(
        "personas",
        "summary_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=True,
    )
    op.alter_column(
        "personas",
        "completeness_score",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "personas",
        "created_by",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="created_by::uuid",
    )
    op.drop_constraint(op.f("personas_user_id_key"), "personas", type_="unique")
    op.create_index(op.f("ix_personas_user_id"), "personas", ["user_id"], unique=True)
    op.drop_column("personas", "experience")
    op.drop_column("personas", "skills")
    op.drop_column("personas", "preferred_name")
    op.drop_column("personas", "pronouns")
    op.drop_column("personas", "is_deleted")
    op.drop_column("personas", "location")
    op.drop_column("personas", "education")
    op.add_column("resume_templates", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.add_column("resume_templates", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.add_column(
        "resume_templates",
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
    )
    op.alter_column(
        "resume_templates",
        "created_by",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="created_by::uuid",
    )
    op.drop_column("resume_templates", "is_deleted")
    op.add_column("resumes", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.add_column("resumes", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "resumes",
        "created_by",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="created_by::uuid",
    )
    op.drop_column("resumes", "is_deleted")
    op.add_column("users", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.add_column("users", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.add_column(
        "users", sa.Column("version", sa.Integer(), nullable=False, server_default="1")
    )
    op.alter_column(
        "users",
        "created_by",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="created_by::uuid",
    )
    op.drop_column("users", "is_deleted")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "users",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("users", "version")
    op.drop_column("users", "updated_by")
    op.drop_column("users", "deleted_by")
    op.add_column(
        "resumes",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "resumes",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("resumes", "updated_by")
    op.drop_column("resumes", "deleted_by")
    op.add_column(
        "resume_templates",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "resume_templates",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("resume_templates", "version")
    op.drop_column("resume_templates", "updated_by")
    op.drop_column("resume_templates", "deleted_by")
    op.add_column(
        "personas",
        sa.Column(
            "education",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "location",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "personas",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "personas",
        sa.Column(
            "pronouns", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "preferred_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "skills",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "experience",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_personas_user_id"), table_name="personas")
    op.create_unique_constraint(
        op.f("personas_user_id_key"),
        "personas",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "personas",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "personas",
        "completeness_score",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "personas",
        "summary_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=True,
    )
    op.drop_column("personas", "version")
    op.drop_column("personas", "updated_by")
    op.drop_column("personas", "deleted_by")
    op.drop_column("personas", "remote_preference")
    op.drop_column("personas", "work_authorization")
    op.drop_column("personas", "location_country")
    op.drop_column("personas", "location_state")
    op.drop_column("personas", "location_city")
    op.drop_column("personas", "phone")
    op.drop_column("personas", "email")
    op.drop_column("personas", "full_name")
    op.add_column(
        "jobs",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "jobs",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("jobs", "version")
    op.drop_column("jobs", "updated_by")
    op.drop_column("jobs", "deleted_by")
    op.add_column(
        "job_matches",
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "job_matches",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("job_matches", "version")
    op.drop_column("job_matches", "updated_by")
    op.drop_column("job_matches", "deleted_by")
    op.drop_index(op.f("ix_persona_skills_persona_id"), table_name="persona_skills")
    op.drop_index(op.f("ix_persona_skills_name"), table_name="persona_skills")
    op.drop_table("persona_skills")
    op.drop_index(
        op.f("ix_persona_experiences_persona_id"), table_name="persona_experiences"
    )
    op.drop_table("persona_experiences")
    op.drop_index(
        op.f("ix_persona_educations_persona_id"), table_name="persona_educations"
    )
    op.drop_table("persona_educations")
    op.drop_index(
        op.f("ix_persona_career_preferences_persona_id"),
        table_name="persona_career_preferences",
    )
    op.drop_table("persona_career_preferences")
    op.drop_index(
        op.f("ix_persona_behavioral_answers_persona_id"),
        table_name="persona_behavioral_answers",
    )
    op.drop_table("persona_behavioral_answers")
    # ### end Alembic commands ###
