"""feat: implement persona module schema

Revision ID: 7f97b53db79e
Revises: 41c245a52218
Create Date: 2026-02-01 14:38:21.137337

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f97b53db79e"
down_revision: str | Sequence[str] | None = "41c245a52218"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "personas",
        "summary_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "personas",
        "summary_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        nullable=False,
    )
    # ### end Alembic commands ###
