"""add_user_tier_and_governance

Revision ID: b24b82412995
Revises: fa7ad600fd14
Create Date: 2026-02-01 19:44:13.616870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "b24b82412995"
down_revision: Union[str, Sequence[str], None] = "fa7ad600fd14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type first
    subscription_tier = sa.Enum(
        "FREE", "PLUS", "PRO", "PREMIUM", name="subscription_tier"
    )
    subscription_tier.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "persona_behavioral_answers",
        "answer_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=True,
    )
    op.alter_column(
        "persona_experiences",
        "experience_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=True,
    )
    op.alter_column(
        "personas",
        "summary_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_resumes_user_id_created_at_desc"), table_name="resumes")
    op.create_index(
        "ix_resumes_user_id_created_at_desc",
        "resumes",
        ["user_id", "created_at"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.add_column(
        "users",
        sa.Column(
            "tier",
            sa.Enum("FREE", "PLUS", "PRO", "PREMIUM", name="subscription_tier"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tier")
    op.drop_index(
        "ix_resumes_user_id_created_at_desc",
        table_name="resumes",
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_index(
        op.f("ix_resumes_user_id_created_at_desc"),
        "resumes",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "personas",
        "summary_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=True,
    )
    op.alter_column(
        "persona_experiences",
        "experience_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=True,
    )
    op.alter_column(
        "persona_behavioral_answers",
        "answer_embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
