"""feat: add agent interventions and sync schema

Revision ID: ecc6b0fa9ff1
Revises: e296d106876e
Create Date: 2026-02-06 01:39:07.096204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.core.security.encryption import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "ecc6b0fa9ff1"
down_revision: Union[str, Sequence[str], None] = "e296d106876e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portal_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("cookies", EncryptedString(), nullable=True),
        sa.Column("local_storage", EncryptedString(), nullable=True),
        sa.Column("is_logged_in", sa.Boolean(), nullable=True),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portal_sessions_domain"), "portal_sessions", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_portal_sessions_user_id"), "portal_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "agent_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_sessions_user_id"), "agent_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "agent_tasks",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("SCOUT", "APPLICANT", "REGISTRAR", name="agenttype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="taskstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="taskpriority"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_tasks_status"), "agent_tasks", ["status"], unique=False
    )
    op.create_index(
        "ix_agent_tasks_status_priority",
        "agent_tasks",
        ["status", "priority"],
        unique=False,
    )
    op.create_index(
        "ix_agent_tasks_user_created",
        "agent_tasks",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_tasks_user_id"), "agent_tasks", ["user_id"], unique=False
    )
    op.create_table(
        "agent_interventions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_interventions_session_id"),
        "agent_interventions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_interventions_user_id"),
        "agent_interventions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "discovered_jobs",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("description_snippet", sa.Text(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column(
            "match_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_platform", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovered_jobs_session_id"),
        "discovered_jobs",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_discovered_jobs_session_status",
        "discovered_jobs",
        ["session_id", "status"],
        unique=False,
    )
    op.create_table(
        "application_attempts",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("discovered_job_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "fields_submitted", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("confirmation_screenshot_path", sa.String(length=512), nullable=True),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["discovered_job_id"],
            ["discovered_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["agent_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "applications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("job_title", sa.String(length=255), nullable=False),
        sa.Column("job_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WISHLIST",
                "APPLIED",
                "SCREENING",
                "INTERVIEW",
                "OFFER",
                "REJECTED",
                "ACCEPTED",
                "WITHDRAWN",
                name="applicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("resume_id", sa.UUID(), nullable=True),
        sa.Column("cover_letter_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("excitement_rating", sa.Integer(), nullable=True),
        sa.Column("next_follow_up", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_applications_user_created_at_desc",
        "applications",
        ["user_id", "created_at"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_index(
        op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False
    )
    op.create_index(
        "ix_applications_user_next_follow_up",
        "applications",
        ["user_id", "next_follow_up"],
        unique=False,
    )
    op.create_index(
        "ix_applications_user_status",
        "applications",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "application_events",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=50), nullable=True),
        sa.Column("to_status", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_events_application_id"),
        "application_events",
        ["application_id"],
        unique=False,
    )
    op.alter_column(
        "personas",
        "work_authorization",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "CITIZEN",
            "PERMANENT_RESIDENT",
            "H1B",
            "L1",
            "F1_OPT",
            "J1",
            "TN",
            "OTHER",
            "NOT_REQUIRED",
            name="workauthorization",
        ),
        existing_nullable=False,
        postgresql_using="work_authorization::workauthorization",
    )
    op.drop_index(op.f("ix_resumes_user_id_created_at_desc"), table_name="resumes")
    op.create_index(
        "ix_resumes_user_id_created_at_desc",
        "resumes",
        ["user_id", "created_at"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.add_column(
        "user_profiles", sa.Column("experience", EncryptedString(), nullable=False)
    )
    op.add_column(
        "user_profiles", sa.Column("education", EncryptedString(), nullable=False)
    )
    op.add_column(
        "user_profiles", sa.Column("skills", EncryptedString(), nullable=False)
    )
    op.add_column(
        "user_profiles", sa.Column("languages", EncryptedString(), nullable=False)
    )
    op.add_column(
        "user_profiles", sa.Column("certifications", EncryptedString(), nullable=False)
    )
    op.add_column(
        "user_profiles",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("user_profiles", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.add_column("user_profiles", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column("user_profiles", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.add_column("user_profiles", sa.Column("version", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "version")
    op.drop_column("user_profiles", "updated_by")
    op.drop_column("user_profiles", "created_by")
    op.drop_column("user_profiles", "deleted_by")
    op.drop_column("user_profiles", "deleted_at")
    op.drop_column("user_profiles", "certifications")
    op.drop_column("user_profiles", "languages")
    op.drop_column("user_profiles", "skills")
    op.drop_column("user_profiles", "education")
    op.drop_column("user_profiles", "experience")
    op.drop_index(
        "ix_resumes_user_id_created_at_desc",
        table_name="resumes",
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_index(
        op.f("ix_resumes_user_id_created_at_desc"),
        "resumes",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "personas",
        "work_authorization",
        existing_type=sa.Enum(
            "CITIZEN",
            "PERMANENT_RESIDENT",
            "H1B",
            "L1",
            "F1_OPT",
            "J1",
            "TN",
            "OTHER",
            "NOT_REQUIRED",
            name="workauthorization",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_application_events_application_id"), table_name="application_events"
    )
    op.drop_table("application_events")
    op.drop_index("ix_applications_user_status", table_name="applications")
    op.drop_index("ix_applications_user_next_follow_up", table_name="applications")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index(
        "ix_applications_user_created_at_desc",
        table_name="applications",
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.drop_table("applications")
    op.drop_table("application_attempts")
    op.drop_index("ix_discovered_jobs_session_status", table_name="discovered_jobs")
    op.drop_index(op.f("ix_discovered_jobs_session_id"), table_name="discovered_jobs")
    op.drop_table("discovered_jobs")
    op.drop_index(
        op.f("ix_agent_interventions_user_id"), table_name="agent_interventions"
    )
    op.drop_index(
        op.f("ix_agent_interventions_session_id"), table_name="agent_interventions"
    )
    op.drop_table("agent_interventions")
    op.drop_index(op.f("ix_agent_tasks_user_id"), table_name="agent_tasks")
    op.drop_index("ix_agent_tasks_user_created", table_name="agent_tasks")
    op.drop_index("ix_agent_tasks_status_priority", table_name="agent_tasks")
    op.drop_index(op.f("ix_agent_tasks_status"), table_name="agent_tasks")
    op.drop_table("agent_tasks")
    op.drop_index(op.f("ix_agent_sessions_user_id"), table_name="agent_sessions")
    op.drop_table("agent_sessions")
    op.drop_index(op.f("ix_portal_sessions_user_id"), table_name="portal_sessions")
    op.drop_index(op.f("ix_portal_sessions_domain"), table_name="portal_sessions")
    op.drop_table("portal_sessions")
    # ### end Alembic commands ###
