"""feat: implement resume module schema

Revision ID: ef5159927432
Revises: 7f97b53db79e
Create Date: 2026-02-01 14:45:05.454614

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ef5159927432"
down_revision: str | Sequence[str] | None = "7f97b53db79e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
