"""add_persona_links_and_summary

Revision ID: f3829d76fdbf
Revises: fa7ad600fd14
Create Date: 2026-02-05 00:05:53.379477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.core.security.encryption
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "f3829d76fdbf"
down_revision: Union[str, Sequence[str], None] = "fa7ad600fd14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persona_certifications",
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("credential_id", sa.String(length=255), nullable=True),
        sa.Column("credential_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persona_certifications_persona_id"),
        "persona_certifications",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "persona_projects",
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("github_url", sa.String(length=500), nullable=True),
        sa.Column("technologies", sa.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_persona_projects_persona_id"),
        "persona_projects",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "experience_enhancements",
        sa.Column("experience_id", sa.UUID(), nullable=False),
        sa.Column("field_enhanced", sa.String(length=50), nullable=False),
        sa.Column("original_content", sa.Text(), nullable=False),
        sa.Column("enhanced_content", sa.Text(), nullable=False),
        sa.Column("enhancement_type", sa.String(length=50), nullable=False),
        sa.Column("confidence_level", sa.String(length=20), nullable=False),
        sa.Column("user_approved", sa.Boolean(), nullable=True),
        sa.Column("user_modified", sa.Boolean(), nullable=False),
        sa.Column("user_final_content", sa.Text(), nullable=True),
        sa.Column(
            "sources_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            ["persona_experiences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_enhancements_experience_id"),
        "experience_enhancements",
        ["experience_id"],
        unique=False,
    )
    op.alter_column(
        "persona_behavioral_answers",
        "answer",
        existing_type=sa.VARCHAR(),
        type_=src.core.security.encryption.EncryptedString(),
        existing_nullable=False,
    )
    op.add_column(
        "persona_experiences",
        sa.Column("company_url", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "persona_experiences",
        sa.Column("location", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "persona_experiences",
        sa.Column("employment_type", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "persona_experiences",
        sa.Column(
            "is_current", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "persona_experiences",
        sa.Column("description_original", sa.Text(), nullable=True),
    )
    op.add_column(
        "persona_experiences",
        sa.Column(
            "bullets_original",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column(
        "persona_experiences",
        sa.Column("description_enhanced", sa.Text(), nullable=True),
    )
    op.add_column(
        "persona_experiences",
        sa.Column(
            "bullets_enhanced",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column(
        "persona_experiences", sa.Column("description_active", sa.Text(), nullable=True)
    )
    op.add_column(
        "persona_experiences",
        sa.Column(
            "bullets_active",
            sa.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column(
        "persona_experiences",
        sa.Column("order", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    op.drop_column("persona_experiences", "description")
    op.add_column(
        "persona_skills", sa.Column("years_of_experience", sa.Integer(), nullable=True)
    )
    op.execute(
        sa.text("""
        DO $$ BEGIN
            CREATE TYPE skillsource AS ENUM ('USER_DECLARED', 'RESUME_PARSED', 'EXPERIENCE_INFERRED', 'CERTIFICATION', 'VERIFIED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    )
    op.add_column(
        "persona_skills",
        sa.Column(
            "source",
            sa.Enum(
                "USER_DECLARED",
                "RESUME_PARSED",
                "EXPERIENCE_INFERRED",
                "CERTIFICATION",
                "VERIFIED",
                name="skillsource",
            ),
            nullable=False,
            server_default=sa.text("'USER_DECLARED'"),
        ),
    )
    op.add_column(
        "persona_skills",
        sa.Column("source_detail", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "persona_skills",
        sa.Column(
            "verified", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "persona_skills",
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "persona_skills",
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column(
        "personas", sa.Column("linkedin_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "personas", sa.Column("github_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "personas", sa.Column("portfolio_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "personas", sa.Column("website_url", sa.String(length=255), nullable=True)
    )
    op.add_column("personas", sa.Column("summary_original", sa.Text(), nullable=True))
    op.add_column("personas", sa.Column("summary_enhanced", sa.Text(), nullable=True))
    op.add_column("personas", sa.Column("summary_active", sa.Text(), nullable=True))
    op.add_column(
        "personas",
        sa.Column(
            "requires_sponsorship",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "personas",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
    )
    op.add_column(
        "personas",
        sa.Column("embedding_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "personas",
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    op.alter_column(
        "personas",
        "work_authorization",
        existing_type=postgresql.ENUM(
            "CITIZEN",
            "PERMANENT_RESIDENT",
            "H1B",
            "L1",
            "F1_OPT",
            "J1",
            "TN",
            "OTHER",
            "NOT_REQUIRED",
            name="workauthorization",
        ),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=False,
        postgresql_using="ARRAY[work_authorization::text]",
    )
    op.add_column("resumes", sa.Column("persona_id", sa.UUID(), nullable=True))
    op.execute(
        sa.text(
            "UPDATE resumes SET persona_id = personas.id FROM personas WHERE resumes.user_id = personas.user_id"
        )
    )
    op.execute(sa.text("DELETE FROM resumes WHERE persona_id IS NULL"))
    op.alter_column("resumes", "persona_id", nullable=False)
    op.add_column(
        "resumes", sa.Column("target_role", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "resumes", sa.Column("target_industry", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "resumes", sa.Column("target_company", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "resumes",
        sa.Column(
            "content_selection",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    op.add_column(
        "resumes", sa.Column("pdf_file_path", sa.String(length=512), nullable=True)
    )
    op.add_column(
        "resumes", sa.Column("docx_file_path", sa.String(length=512), nullable=True)
    )
    op.add_column(
        "resumes", sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index(op.f("ix_resumes_user_id_created_at_desc"), table_name="resumes")
    op.create_index(
        "ix_resumes_user_id_created_at_desc",
        "resumes",
        ["user_id", "created_at"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_foreign_key(None, "resumes", "personas", ["persona_id"], ["id"])
    op.add_column("user_settings", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.add_column("user_settings", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column("user_settings", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.add_column(
        "user_settings",
        sa.Column("version", sa.Integer(), nullable=False, server_default=sa.text("1")),
    )
    op.alter_column(
        "user_settings",
        "theme",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'system'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "language",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
        existing_server_default=sa.text("'en'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'UTC'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "date_format",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'YYYY-MM-DD'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "email_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_settings",
        "push_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_settings",
        "sms_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_settings",
        "job_alerts",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_settings",
        "weekly_digest",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_settings",
        "match_threshold",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("70"),
    )
    op.alter_column(
        "user_settings",
        "preferred_work_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'any'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "salary_visible",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_settings",
        "auto_apply_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_settings",
        "auto_apply_limit",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("5"),
    )
    op.alter_column(
        "user_settings",
        "auto_apply_min_match",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("85"),
    )
    op.alter_column(
        "user_settings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "user_settings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "user_settings",
        "deleted_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_settings",
        "deleted_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_settings",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "user_settings",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "user_settings",
        "auto_apply_min_match",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("85"),
    )
    op.alter_column(
        "user_settings",
        "auto_apply_limit",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("5"),
    )
    op.alter_column(
        "user_settings",
        "auto_apply_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_settings",
        "salary_visible",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_settings",
        "preferred_work_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'any'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "match_threshold",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("70"),
    )
    op.alter_column(
        "user_settings",
        "weekly_digest",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_settings",
        "job_alerts",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_settings",
        "sms_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_settings",
        "push_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_settings",
        "email_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_settings",
        "date_format",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'YYYY-MM-DD'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'UTC'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "language",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        existing_server_default=sa.text("'en'::character varying"),
    )
    op.alter_column(
        "user_settings",
        "theme",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'system'::character varying"),
    )
    op.drop_column("user_settings", "version")
    op.drop_column("user_settings", "updated_by")
    op.drop_column("user_settings", "created_by")
    op.drop_column("user_settings", "deleted_by")
    op.drop_constraint(None, "resumes", type_="foreignkey")
    op.drop_index(
        "ix_resumes_user_id_created_at_desc",
        table_name="resumes",
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_index(
        op.f("ix_resumes_user_id_created_at_desc"),
        "resumes",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_column("resumes", "last_used_at")
    op.drop_column("resumes", "docx_file_path")
    op.drop_column("resumes", "pdf_file_path")
    op.drop_column("resumes", "content_selection")
    op.drop_column("resumes", "target_company")
    op.drop_column("resumes", "target_industry")
    op.drop_column("resumes", "target_role")
    op.drop_column("resumes", "persona_id")
    op.alter_column(
        "personas",
        "work_authorization",
        existing_type=sa.ARRAY(sa.String()),
        type_=postgresql.ENUM(
            "CITIZEN",
            "PERMANENT_RESIDENT",
            "H1B",
            "L1",
            "F1_OPT",
            "J1",
            "TN",
            "OTHER",
            "NOT_REQUIRED",
            name="workauthorization",
        ),
        existing_nullable=False,
    )
    op.drop_column("personas", "last_updated_at")
    op.drop_column("personas", "embedding_updated_at")
    op.drop_column("personas", "embedding")
    op.drop_column("personas", "requires_sponsorship")
    op.drop_column("personas", "summary_active")
    op.drop_column("personas", "summary_enhanced")
    op.drop_column("personas", "summary_original")
    op.drop_column("personas", "website_url")
    op.drop_column("personas", "portfolio_url")
    op.drop_column("personas", "github_url")
    op.drop_column("personas", "linkedin_url")
    op.drop_column("persona_skills", "evidence")
    op.drop_column("persona_skills", "verified_at")
    op.drop_column("persona_skills", "verified")
    op.drop_column("persona_skills", "source_detail")
    op.drop_column("persona_skills", "source")
    op.drop_column("persona_skills", "years_of_experience")
    op.add_column(
        "persona_experiences",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("persona_experiences", "order")
    op.drop_column("persona_experiences", "bullets_active")
    op.drop_column("persona_experiences", "description_active")
    op.drop_column("persona_experiences", "bullets_enhanced")
    op.drop_column("persona_experiences", "description_enhanced")
    op.drop_column("persona_experiences", "bullets_original")
    op.drop_column("persona_experiences", "description_original")
    op.drop_column("persona_experiences", "is_current")
    op.drop_column("persona_experiences", "employment_type")
    op.drop_column("persona_experiences", "location")
    op.drop_column("persona_experiences", "company_url")
    op.alter_column(
        "persona_behavioral_answers",
        "answer",
        existing_type=src.core.security.encryption.EncryptedString(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_experience_enhancements_experience_id"),
        table_name="experience_enhancements",
    )
    op.drop_table("experience_enhancements")
    op.drop_index(op.f("ix_persona_projects_persona_id"), table_name="persona_projects")
    op.drop_table("persona_projects")
    op.drop_index(
        op.f("ix_persona_certifications_persona_id"),
        table_name="persona_certifications",
    )
    op.drop_table("persona_certifications")
    # ### end Alembic commands ###
