"""feat: implement comprehensive resume module tables

Revision ID: fa7ad600fd14
Revises: 6e7a4aeb9d95
Create Date: 2026-02-01 15:16:05.856922

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa7ad600fd14"
down_revision: str | Sequence[str] | None = "6e7a4aeb9d95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM types manually if they are used in add_column but not create_table
    sa.Enum(
        "CLASSIC",
        "MODERN",
        "TECHNICAL",
        "EXECUTIVE",
        "CREATIVE",
        name="templatecategory",
    ).create(op.get_bind())
    sa.Enum("SCRATCH", "UPLOAD", "PERSONA", "LINKEDIN", name="resumesource").create(
        op.get_bind()
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ats_analyses",
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("format_score", sa.Float(), nullable=True),
        sa.Column("content_score", sa.Float(), nullable=True),
        sa.Column("keyword_score", sa.Float(), nullable=True),
        sa.Column(
            "recommendations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ats_analyses_resume_id"), "ats_analyses", ["resume_id"], unique=False
    )
    op.create_table(
        "resume_sections",
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column(
            "section_type",
            sa.Enum(
                "SUMMARY",
                "EXPERIENCE",
                "EDUCATION",
                "SKILLS",
                "PROJECTS",
                "CERTIFICATIONS",
                "LANGUAGES",
                "CUSTOM",
                name="sectiontype",
            ),
            nullable=False,
        ),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_sections_resume_id"),
        "resume_sections",
        ["resume_id"],
        unique=False,
    )
    op.create_table(
        "resume_versions",
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "content_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_versions_resume_id"),
        "resume_versions",
        ["resume_id"],
        unique=False,
    )
    op.add_column(
        "resume_templates",
        sa.Column("thumbnail_url", sa.String(length=512), nullable=True),
    )
    op.add_column(
        "resume_templates", sa.Column("template_file", sa.Text(), nullable=False)
    )
    op.add_column(
        "resume_templates",
        sa.Column(
            "category",
            sa.Enum(
                "CLASSIC",
                "MODERN",
                "TECHNICAL",
                "EXECUTIVE",
                "CREATIVE",
                name="templatecategory",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "resume_templates", sa.Column("is_ats_optimized", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "resume_templates",
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.alter_column(
        "resume_templates",
        "id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="id::uuid",
    )
    op.drop_column("resume_templates", "schema")
    op.drop_column("resume_templates", "is_active")
    op.add_column("resumes", sa.Column("word_count", sa.Integer(), nullable=True))
    op.add_column(
        "resumes", sa.Column("file_path", sa.String(length=512), nullable=True)
    )
    op.add_column(
        "resumes",
        sa.Column(
            "created_from",
            sa.Enum("SCRATCH", "UPLOAD", "PERSONA", "LINKEDIN", name="resumesource"),
            nullable=False,
        ),
    )
    op.alter_column(
        "resumes",
        "template_id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="template_id::uuid",
    )
    op.alter_column(
        "resumes",
        "ats_score",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_resumes_user_id"), "resumes", ["user_id"], unique=False)
    op.create_index(
        "ix_resumes_user_id_created_at_desc",
        "resumes",
        ["user_id", "created_at"],
        unique=False,
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.create_index(
        "ix_resumes_user_id_is_primary",
        "resumes",
        ["user_id", "is_primary"],
        unique=False,
    )
    op.create_foreign_key(None, "resumes", "resume_templates", ["template_id"], ["id"])
    op.drop_column("resumes", "docx_url")
    op.drop_column("resumes", "pdf_url")
    op.drop_column("resumes", "analysis_results")
    op.drop_column("resumes", "analyzed_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resumes",
        sa.Column(
            "analyzed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "resumes",
        sa.Column(
            "analysis_results",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "resumes",
        sa.Column(
            "pdf_url", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "resumes",
        sa.Column(
            "docx_url", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "resumes", type_="foreignkey")
    op.drop_index("ix_resumes_user_id_is_primary", table_name="resumes")
    op.drop_index(
        "ix_resumes_user_id_created_at_desc",
        table_name="resumes",
        postgresql_using="btree",
        postgresql_ops={"created_at": "desc"},
    )
    op.drop_index(op.f("ix_resumes_user_id"), table_name="resumes")
    op.alter_column(
        "resumes",
        "ats_score",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "resumes",
        "template_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_column("resumes", "created_from")
    op.drop_column("resumes", "file_path")
    op.drop_column("resumes", "word_count")
    op.add_column(
        "resume_templates",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "resume_templates",
        sa.Column(
            "schema",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "resume_templates",
        "id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("resume_templates", "settings")
    op.drop_column("resume_templates", "is_ats_optimized")
    op.drop_column("resume_templates", "category")
    op.drop_column("resume_templates", "template_file")
    op.drop_column("resume_templates", "thumbnail_url")
    op.drop_index(op.f("ix_resume_versions_resume_id"), table_name="resume_versions")
    op.drop_table("resume_versions")
    op.drop_index(op.f("ix_resume_sections_resume_id"), table_name="resume_sections")
    op.drop_table("resume_sections")
    op.drop_index(op.f("ix_ats_analyses_resume_id"), table_name="ats_analyses")
    op.drop_table("ats_analyses")
    # ### end Alembic commands ###
