from typing import Protocol, runtime_checkable
from uuid import UUID

from src.modules.resume.domain.models import Resume, ResumeTemplate


@runtime_checkable
class ResumeRepository(Protocol):
    async def get_by_id(self, resume_id: UUID) -> Resume | None: ...

    async def get_all_by_user_id(self, user_id: UUID) -> list[Resume]: ...

    async def get_primary_by_user_id(self, user_id: UUID) -> Resume | None: ...

    async def save(self, resume: Resume) -> Resume: ...

    async def delete(self, resume_id: UUID) -> None: ...

    async def get_template_by_id(self, template_id: UUID) -> ResumeTemplate | None: ...

    async def get_active_templates(self) -> list[ResumeTemplate]: ...
