// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package persistence

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type Application struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	UserID                  pgtype.UUID        `db:"user_id" json:"user_id"`
	JobID                   pgtype.UUID        `db:"job_id" json:"job_id"`
	ResumeID                pgtype.UUID        `db:"resume_id" json:"resume_id"`
	ResumeSnapshot          []byte             `db:"resume_snapshot" json:"resume_snapshot"`
	CoverLetterID           pgtype.UUID        `db:"cover_letter_id" json:"cover_letter_id"`
	CoverLetterSnapshot     pgtype.Text        `db:"cover_letter_snapshot" json:"cover_letter_snapshot"`
	Answers                 []byte             `db:"answers" json:"answers"`
	Status                  pgtype.Text        `db:"status" json:"status"`
	SubmissionMode          pgtype.Text        `db:"submission_mode" json:"submission_mode"`
	SubmittedAt             pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	SubmissionScreenshotUrl pgtype.Text        `db:"submission_screenshot_url" json:"submission_screenshot_url"`
	ErrorMessage            pgtype.Text        `db:"error_message" json:"error_message"`
	RetryCount              pgtype.Int4        `db:"retry_count" json:"retry_count"`
	Timeline                []byte             `db:"timeline" json:"timeline"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AuditLog struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ActorID       pgtype.UUID        `db:"actor_id" json:"actor_id"`
	ActorType     string             `db:"actor_type" json:"actor_type"`
	Action        string             `db:"action" json:"action"`
	ResourceType  string             `db:"resource_type" json:"resource_type"`
	ResourceID    pgtype.UUID        `db:"resource_id" json:"resource_id"`
	IpAddressHash pgtype.Text        `db:"ip_address_hash" json:"ip_address_hash"`
	UserAgentHash pgtype.Text        `db:"user_agent_hash" json:"user_agent_hash"`
	OldValues     []byte             `db:"old_values" json:"old_values"`
	NewValues     []byte             `db:"new_values" json:"new_values"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Success       bool               `db:"success" json:"success"`
	ErrorMessage  pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuditLogs202601 struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ActorID       pgtype.UUID        `db:"actor_id" json:"actor_id"`
	ActorType     string             `db:"actor_type" json:"actor_type"`
	Action        string             `db:"action" json:"action"`
	ResourceType  string             `db:"resource_type" json:"resource_type"`
	ResourceID    pgtype.UUID        `db:"resource_id" json:"resource_id"`
	IpAddressHash pgtype.Text        `db:"ip_address_hash" json:"ip_address_hash"`
	UserAgentHash pgtype.Text        `db:"user_agent_hash" json:"user_agent_hash"`
	OldValues     []byte             `db:"old_values" json:"old_values"`
	NewValues     []byte             `db:"new_values" json:"new_values"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Success       bool               `db:"success" json:"success"`
	ErrorMessage  pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuditLogs202602 struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ActorID       pgtype.UUID        `db:"actor_id" json:"actor_id"`
	ActorType     string             `db:"actor_type" json:"actor_type"`
	Action        string             `db:"action" json:"action"`
	ResourceType  string             `db:"resource_type" json:"resource_type"`
	ResourceID    pgtype.UUID        `db:"resource_id" json:"resource_id"`
	IpAddressHash pgtype.Text        `db:"ip_address_hash" json:"ip_address_hash"`
	UserAgentHash pgtype.Text        `db:"user_agent_hash" json:"user_agent_hash"`
	OldValues     []byte             `db:"old_values" json:"old_values"`
	NewValues     []byte             `db:"new_values" json:"new_values"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Success       bool               `db:"success" json:"success"`
	ErrorMessage  pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AutomationSetting struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Mode          pgtype.Text        `db:"mode" json:"mode"`
	DailyLimit    pgtype.Int4        `db:"daily_limit" json:"daily_limit"`
	WeeklyLimit   pgtype.Int4        `db:"weekly_limit" json:"weekly_limit"`
	MinMatchScore pgtype.Int4        `db:"min_match_score" json:"min_match_score"`
	ActiveHours   []byte             `db:"active_hours" json:"active_hours"`
	PausedUntil   pgtype.Timestamptz `db:"paused_until" json:"paused_until"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CompanyBlacklist struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	CompanyName           string             `db:"company_name" json:"company_name"`
	CompanyNameNormalized string             `db:"company_name_normalized" json:"company_name_normalized"`
	Reason                pgtype.Text        `db:"reason" json:"reason"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ConsentPurpose struct {
	ID          string             `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	Required    pgtype.Bool        `db:"required" json:"required"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CoverLetter struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	JobID     pgtype.UUID        `db:"job_id" json:"job_id"`
	ResumeID  pgtype.UUID        `db:"resume_id" json:"resume_id"`
	Content   string             `db:"content" json:"content"`
	Tone      pgtype.Text        `db:"tone" json:"tone"`
	Length    pgtype.Text        `db:"length" json:"length"`
	Emphasis  []byte             `db:"emphasis" json:"emphasis"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Job struct {
	ID                   pgtype.UUID         `db:"id" json:"id"`
	ExternalID           string              `db:"external_id" json:"external_id"`
	Source               string              `db:"source" json:"source"`
	CompanyName          string              `db:"company_name" json:"company_name"`
	CompanyLogoUrl       pgtype.Text         `db:"company_logo_url" json:"company_logo_url"`
	CompanySize          pgtype.Text         `db:"company_size" json:"company_size"`
	CompanyIndustry      pgtype.Text         `db:"company_industry" json:"company_industry"`
	Title                string              `db:"title" json:"title"`
	Description          string              `db:"description" json:"description"`
	Requirements         []byte              `db:"requirements" json:"requirements"`
	NiceToHaves          []byte              `db:"nice_to_haves" json:"nice_to_haves"`
	Location             []byte              `db:"location" json:"location"`
	IsRemote             pgtype.Bool         `db:"is_remote" json:"is_remote"`
	SalaryMin            pgtype.Int4         `db:"salary_min" json:"salary_min"`
	SalaryMax            pgtype.Int4         `db:"salary_max" json:"salary_max"`
	SalaryCurrency       pgtype.Text         `db:"salary_currency" json:"salary_currency"`
	EmploymentType       pgtype.Text         `db:"employment_type" json:"employment_type"`
	ExperienceLevel      pgtype.Text         `db:"experience_level" json:"experience_level"`
	ApplyUrl             string              `db:"apply_url" json:"apply_url"`
	AtsPlatform          pgtype.Text         `db:"ats_platform" json:"ats_platform"`
	DescriptionEmbedding *pgvector_go.Vector `db:"description_embedding" json:"description_embedding"`
	Status               pgtype.Text         `db:"status" json:"status"`
	PostedAt             pgtype.Timestamptz  `db:"posted_at" json:"posted_at"`
	ExpiresAt            pgtype.Timestamptz  `db:"expires_at" json:"expires_at"`
	LastSeenAt           pgtype.Timestamptz  `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt            pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type JobMatch struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	JobID          pgtype.UUID        `db:"job_id" json:"job_id"`
	OverallScore   int32              `db:"overall_score" json:"overall_score"`
	ScoreBreakdown []byte             `db:"score_breakdown" json:"score_breakdown"`
	Status         pgtype.Text        `db:"status" json:"status"`
	MatchedAt      pgtype.Timestamptz `db:"matched_at" json:"matched_at"`
	ViewedAt       pgtype.Timestamptz `db:"viewed_at" json:"viewed_at"`
}

type Persona struct {
	ID                    pgtype.UUID         `db:"id" json:"id"`
	UserID                pgtype.UUID         `db:"user_id" json:"user_id"`
	FullNameEncrypted     []byte              `db:"full_name_encrypted" json:"full_name_encrypted"`
	PreferredName         pgtype.Text         `db:"preferred_name" json:"preferred_name"`
	Pronouns              pgtype.Text         `db:"pronouns" json:"pronouns"`
	Location              []byte              `db:"location" json:"location"`
	WorkAuthorization     pgtype.Text         `db:"work_authorization" json:"work_authorization"`
	Experience            []byte              `db:"experience" json:"experience"`
	Education             []byte              `db:"education" json:"education"`
	Skills                []byte              `db:"skills" json:"skills"`
	Certifications        []byte              `db:"certifications" json:"certifications"`
	Preferences           []byte              `db:"preferences" json:"preferences"`
	Personality           []byte              `db:"personality" json:"personality"`
	BehavioralStories     []byte              `db:"behavioral_stories" json:"behavioral_stories"`
	SummaryEmbedding      *pgvector_go.Vector `db:"summary_embedding" json:"summary_embedding"`
	SkillsEmbedding       *pgvector_go.Vector `db:"skills_embedding" json:"skills_embedding"`
	CompletenessScore     pgtype.Int4         `db:"completeness_score" json:"completeness_score"`
	CompletenessBreakdown []byte              `db:"completeness_breakdown" json:"completeness_breakdown"`
	Version               pgtype.Int4         `db:"version" json:"version"`
	CreatedAt             pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type Resume struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	Name            string             `db:"name" json:"name"`
	TemplateID      string             `db:"template_id" json:"template_id"`
	Content         []byte             `db:"content" json:"content"`
	PdfUrl          pgtype.Text        `db:"pdf_url" json:"pdf_url"`
	DocxUrl         pgtype.Text        `db:"docx_url" json:"docx_url"`
	AtsScore        pgtype.Int4        `db:"ats_score" json:"ats_score"`
	AnalysisResults []byte             `db:"analysis_results" json:"analysis_results"`
	AnalyzedAt      pgtype.Timestamptz `db:"analyzed_at" json:"analyzed_at"`
	IsPrimary       pgtype.Bool        `db:"is_primary" json:"is_primary"`
	Version         pgtype.Int4        `db:"version" json:"version"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	ExternalID            pgtype.UUID        `db:"external_id" json:"external_id"`
	EmailEncrypted        []byte             `db:"email_encrypted" json:"email_encrypted"`
	EmailHash             string             `db:"email_hash" json:"email_hash"`
	PhoneEncrypted        []byte             `db:"phone_encrypted" json:"phone_encrypted"`
	PasswordHash          string             `db:"password_hash" json:"password_hash"`
	MfaEnabled            pgtype.Bool        `db:"mfa_enabled" json:"mfa_enabled"`
	MfaSecretEncrypted    []byte             `db:"mfa_secret_encrypted" json:"mfa_secret_encrypted"`
	Status                pgtype.Text        `db:"status" json:"status"`
	EmailVerified         pgtype.Bool        `db:"email_verified" json:"email_verified"`
	EmailVerifiedAt       pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	SubscriptionTier      pgtype.Text        `db:"subscription_tier" json:"subscription_tier"`
	SubscriptionExpiresAt pgtype.Timestamptz `db:"subscription_expires_at" json:"subscription_expires_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	LastLoginAt           pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	DataRegion            pgtype.Text        `db:"data_region" json:"data_region"`
	GovernanceMetadata    []byte             `db:"governance_metadata" json:"governance_metadata"`
}

type UserConsent struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	PurposeID      string             `db:"purpose_id" json:"purpose_id"`
	Granted        bool               `db:"granted" json:"granted"`
	GrantedAt      pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	WithdrawnAt    pgtype.Timestamptz `db:"withdrawn_at" json:"withdrawn_at"`
	IpAddressHash  pgtype.Text        `db:"ip_address_hash" json:"ip_address_hash"`
	UserAgentHash  pgtype.Text        `db:"user_agent_hash" json:"user_agent_hash"`
	ConsentVersion pgtype.Text        `db:"consent_version" json:"consent_version"`
}
