// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personas.sql

package persistence

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersona = `-- name: CreatePersona :one
INSERT INTO personas (
    user_id,
    full_name_encrypted,
    preferred_name,
    pronouns,
    location,
    work_authorization,
    experience,
    education,
    skills,
    certifications,
    preferences,
    personality,
    behavioral_stories,
    completeness_score,
    completeness_breakdown
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, user_id, full_name_encrypted, preferred_name, pronouns, location, work_authorization, experience, education, skills, certifications, preferences, personality, behavioral_stories, completeness_score, completeness_breakdown, version, created_at, updated_at
`

type CreatePersonaParams struct {
	UserID                pgtype.UUID `db:"user_id" json:"user_id"`
	FullNameEncrypted     []byte      `db:"full_name_encrypted" json:"full_name_encrypted"`
	PreferredName         pgtype.Text `db:"preferred_name" json:"preferred_name"`
	Pronouns              pgtype.Text `db:"pronouns" json:"pronouns"`
	Location              []byte      `db:"location" json:"location"`
	WorkAuthorization     pgtype.Text `db:"work_authorization" json:"work_authorization"`
	Experience            []byte      `db:"experience" json:"experience"`
	Education             []byte      `db:"education" json:"education"`
	Skills                []byte      `db:"skills" json:"skills"`
	Certifications        []byte      `db:"certifications" json:"certifications"`
	Preferences           []byte      `db:"preferences" json:"preferences"`
	Personality           []byte      `db:"personality" json:"personality"`
	BehavioralStories     []byte      `db:"behavioral_stories" json:"behavioral_stories"`
	CompletenessScore     pgtype.Int4 `db:"completeness_score" json:"completeness_score"`
	CompletenessBreakdown []byte      `db:"completeness_breakdown" json:"completeness_breakdown"`
}

type CreatePersonaRow struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	FullNameEncrypted     []byte             `db:"full_name_encrypted" json:"full_name_encrypted"`
	PreferredName         pgtype.Text        `db:"preferred_name" json:"preferred_name"`
	Pronouns              pgtype.Text        `db:"pronouns" json:"pronouns"`
	Location              []byte             `db:"location" json:"location"`
	WorkAuthorization     pgtype.Text        `db:"work_authorization" json:"work_authorization"`
	Experience            []byte             `db:"experience" json:"experience"`
	Education             []byte             `db:"education" json:"education"`
	Skills                []byte             `db:"skills" json:"skills"`
	Certifications        []byte             `db:"certifications" json:"certifications"`
	Preferences           []byte             `db:"preferences" json:"preferences"`
	Personality           []byte             `db:"personality" json:"personality"`
	BehavioralStories     []byte             `db:"behavioral_stories" json:"behavioral_stories"`
	CompletenessScore     pgtype.Int4        `db:"completeness_score" json:"completeness_score"`
	CompletenessBreakdown []byte             `db:"completeness_breakdown" json:"completeness_breakdown"`
	Version               pgtype.Int4        `db:"version" json:"version"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreatePersona(ctx context.Context, arg CreatePersonaParams) (CreatePersonaRow, error) {
	row := q.db.QueryRow(ctx, createPersona,
		arg.UserID,
		arg.FullNameEncrypted,
		arg.PreferredName,
		arg.Pronouns,
		arg.Location,
		arg.WorkAuthorization,
		arg.Experience,
		arg.Education,
		arg.Skills,
		arg.Certifications,
		arg.Preferences,
		arg.Personality,
		arg.BehavioralStories,
		arg.CompletenessScore,
		arg.CompletenessBreakdown,
	)
	var i CreatePersonaRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullNameEncrypted,
		&i.PreferredName,
		&i.Pronouns,
		&i.Location,
		&i.WorkAuthorization,
		&i.Experience,
		&i.Education,
		&i.Skills,
		&i.Certifications,
		&i.Preferences,
		&i.Personality,
		&i.BehavioralStories,
		&i.CompletenessScore,
		&i.CompletenessBreakdown,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersonaByUserID = `-- name: GetPersonaByUserID :one
SELECT id, user_id, full_name_encrypted, preferred_name, pronouns, location, work_authorization, experience, education, skills, certifications, preferences, personality, behavioral_stories, completeness_score, completeness_breakdown, version, created_at, updated_at FROM personas
WHERE user_id = $1 LIMIT 1
`

type GetPersonaByUserIDRow struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	FullNameEncrypted     []byte             `db:"full_name_encrypted" json:"full_name_encrypted"`
	PreferredName         pgtype.Text        `db:"preferred_name" json:"preferred_name"`
	Pronouns              pgtype.Text        `db:"pronouns" json:"pronouns"`
	Location              []byte             `db:"location" json:"location"`
	WorkAuthorization     pgtype.Text        `db:"work_authorization" json:"work_authorization"`
	Experience            []byte             `db:"experience" json:"experience"`
	Education             []byte             `db:"education" json:"education"`
	Skills                []byte             `db:"skills" json:"skills"`
	Certifications        []byte             `db:"certifications" json:"certifications"`
	Preferences           []byte             `db:"preferences" json:"preferences"`
	Personality           []byte             `db:"personality" json:"personality"`
	BehavioralStories     []byte             `db:"behavioral_stories" json:"behavioral_stories"`
	CompletenessScore     pgtype.Int4        `db:"completeness_score" json:"completeness_score"`
	CompletenessBreakdown []byte             `db:"completeness_breakdown" json:"completeness_breakdown"`
	Version               pgtype.Int4        `db:"version" json:"version"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPersonaByUserID(ctx context.Context, userID pgtype.UUID) (GetPersonaByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getPersonaByUserID, userID)
	var i GetPersonaByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullNameEncrypted,
		&i.PreferredName,
		&i.Pronouns,
		&i.Location,
		&i.WorkAuthorization,
		&i.Experience,
		&i.Education,
		&i.Skills,
		&i.Certifications,
		&i.Preferences,
		&i.Personality,
		&i.BehavioralStories,
		&i.CompletenessScore,
		&i.CompletenessBreakdown,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePersona = `-- name: UpdatePersona :one
UPDATE personas
SET
    full_name_encrypted = COALESCE($2, full_name_encrypted),
    preferred_name = COALESCE($3, preferred_name),
    pronouns = COALESCE($4, pronouns),
    location = COALESCE($5, location),
    work_authorization = COALESCE($6, work_authorization),
    experience = COALESCE($7, experience),
    education = COALESCE($8, education),
    skills = COALESCE($9, skills),
    certifications = COALESCE($10, certifications),
    preferences = COALESCE($11, preferences),
    personality = COALESCE($12, personality),
    behavioral_stories = COALESCE($13, behavioral_stories),
    completeness_score = COALESCE($14, completeness_score),
    completeness_breakdown = COALESCE($15, completeness_breakdown),
    updated_at = NOW(),
    version = version + 1
WHERE user_id = $1
RETURNING id, user_id, full_name_encrypted, preferred_name, pronouns, location, work_authorization, experience, education, skills, certifications, preferences, personality, behavioral_stories, completeness_score, completeness_breakdown, version, created_at, updated_at
`

type UpdatePersonaParams struct {
	UserID                pgtype.UUID `db:"user_id" json:"user_id"`
	FullNameEncrypted     []byte      `db:"full_name_encrypted" json:"full_name_encrypted"`
	PreferredName         pgtype.Text `db:"preferred_name" json:"preferred_name"`
	Pronouns              pgtype.Text `db:"pronouns" json:"pronouns"`
	Location              []byte      `db:"location" json:"location"`
	WorkAuthorization     pgtype.Text `db:"work_authorization" json:"work_authorization"`
	Experience            []byte      `db:"experience" json:"experience"`
	Education             []byte      `db:"education" json:"education"`
	Skills                []byte      `db:"skills" json:"skills"`
	Certifications        []byte      `db:"certifications" json:"certifications"`
	Preferences           []byte      `db:"preferences" json:"preferences"`
	Personality           []byte      `db:"personality" json:"personality"`
	BehavioralStories     []byte      `db:"behavioral_stories" json:"behavioral_stories"`
	CompletenessScore     pgtype.Int4 `db:"completeness_score" json:"completeness_score"`
	CompletenessBreakdown []byte      `db:"completeness_breakdown" json:"completeness_breakdown"`
}

type UpdatePersonaRow struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	FullNameEncrypted     []byte             `db:"full_name_encrypted" json:"full_name_encrypted"`
	PreferredName         pgtype.Text        `db:"preferred_name" json:"preferred_name"`
	Pronouns              pgtype.Text        `db:"pronouns" json:"pronouns"`
	Location              []byte             `db:"location" json:"location"`
	WorkAuthorization     pgtype.Text        `db:"work_authorization" json:"work_authorization"`
	Experience            []byte             `db:"experience" json:"experience"`
	Education             []byte             `db:"education" json:"education"`
	Skills                []byte             `db:"skills" json:"skills"`
	Certifications        []byte             `db:"certifications" json:"certifications"`
	Preferences           []byte             `db:"preferences" json:"preferences"`
	Personality           []byte             `db:"personality" json:"personality"`
	BehavioralStories     []byte             `db:"behavioral_stories" json:"behavioral_stories"`
	CompletenessScore     pgtype.Int4        `db:"completeness_score" json:"completeness_score"`
	CompletenessBreakdown []byte             `db:"completeness_breakdown" json:"completeness_breakdown"`
	Version               pgtype.Int4        `db:"version" json:"version"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdatePersona(ctx context.Context, arg UpdatePersonaParams) (UpdatePersonaRow, error) {
	row := q.db.QueryRow(ctx, updatePersona,
		arg.UserID,
		arg.FullNameEncrypted,
		arg.PreferredName,
		arg.Pronouns,
		arg.Location,
		arg.WorkAuthorization,
		arg.Experience,
		arg.Education,
		arg.Skills,
		arg.Certifications,
		arg.Preferences,
		arg.Personality,
		arg.BehavioralStories,
		arg.CompletenessScore,
		arg.CompletenessBreakdown,
	)
	var i UpdatePersonaRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullNameEncrypted,
		&i.PreferredName,
		&i.Pronouns,
		&i.Location,
		&i.WorkAuthorization,
		&i.Experience,
		&i.Education,
		&i.Skills,
		&i.Certifications,
		&i.Preferences,
		&i.Personality,
		&i.BehavioralStories,
		&i.CompletenessScore,
		&i.CompletenessBreakdown,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
