from src.modules.persona.domain.schemas import (
    BehavioralAnswerBase,
    BehavioralAnswerCreate,
    BehavioralAnswerRead,
    CareerPreferenceBase,
    CareerPreferenceCreate,
    CareerPreferenceRead,
    CareerPreferenceUpdate,
    EducationBase,
    EducationCreate,
    EducationRead,
    EducationUpdate,
    ExperienceBase,
    ExperienceCreate,
    ExperienceRead,
    ExperienceUpdate,
    PersonaBase,
    PersonaCreate,
    PersonaRead,
    PersonaUpdate,
    SkillBase,
    SkillCreate,
    SkillRead,
    SkillUpdate,
)

# Aliases for compatibility with existing routes
PersonaResponse = PersonaRead

# Re-exporting all schemas for external use from api module
__all__ = [
    "ExperienceBase",
    "ExperienceCreate",
    "ExperienceUpdate",
    "ExperienceRead",
    "EducationBase",
    "EducationCreate",
    "EducationUpdate",
    "EducationRead",
    "SkillBase",
    "SkillCreate",
    "SkillRead",
    "SkillUpdate",
    "CareerPreferenceBase",
    "CareerPreferenceCreate",
    "CareerPreferenceUpdate",
    "CareerPreferenceRead",
    "BehavioralAnswerBase",
    "BehavioralAnswerCreate",
    "BehavioralAnswerRead",
    "PersonaBase",
    "PersonaCreate",
    "PersonaUpdate",
    "PersonaRead",
    "PersonaResponse",
]
